import { Calendar } from '@fullcalendar/core';
window.Calendar = Calendar;
import interaction from '@fullcalendar/interaction';
window.interaction = interaction;
import dayGridPlugin from '@fullcalendar/daygrid';
window.dayGridPlugin = dayGridPlugin;
import timeGridPlugin from '@fullcalendar/timegrid';
window.timeGridPlugin = timeGridPlugin;
import listPlugin from '@fullcalendar/list';
window.listPlugin = listPlugin;
import multiMonth from '@fullcalendar/multimonth';
window.multiMonth = multiMonth;
import bootstrap from '@fullcalendar/bootstrap';
window.bootstrapPlugin = bootstrap;
import google_calendar from '@fullcalendar/google-calendar';
window.googleCalendarPlugin = google_calendar;